// Generated by CoffeeScript 1.8.0
(function() {
let target_elems = document.getElementsByClassName('commit-group-title');
if(target_elems.length >= 1){
  let fool_months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  let prefix = 'Commits on '
  for (let i = 0; i < target_elems.length; i++) {
    let inner_html = target_elems[i].innerHTML;
    let str_index = inner_html.indexOf(prefix);
    let str_arr = inner_html.slice(str_index, -1).replace(',', '').split(' ');
    let year,month,date;
    let genius_form;
    for (let j = 0; j < str_arr.length; j++){
      let v = str_arr[j].replace(/\r?\n/g,"");
      if(parseInt(v) >= 100){
        year = v;
      }else if(1 <= parseInt(v) && parseInt(v) <= 31){
      	date = v;
      }else if(fool_months.indexOf(v) >= 0){
		month = fool_months.indexOf(v) + 1;
	  }
    }
    if(year != undefined && month != undefined && date != undefined){
	  genius_form = [year, month, date].join('/');
      target_elems[i].innerHTML = inner_html.slice(0, str_index) + prefix + genius_form;
	}
  }
}

}).call(this);
